apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment-<userid>
  namespace: ns-<userid>
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
    # enter the path to your image, be sure to include the correct region prefix    
        image: <region-key>.ocir.io/<tenancy-namespace>/<repo-name>:<tag>-<userid>
        ports:
        - containerPort: 80
      imagePullSecrets:
    # enter the name of the secret you created  
      - name: <secret-name>
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service-<userid>
  namespace: ns-<userid>
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: helloworld
