apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment-mahendra
  namespace: ns-mahendra
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
    # enter the path to your image, be sure to include the correct region prefix    
        image: iad.ocir.io/ocuocictrng6/oci_sample_webapp_user1:${BUILDRUN_HASH}
        ports:
        - containerPort: 80
      imagePullSecrets:
    # enter the name of the secret you created  
      - name: ocir-secret-user1
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service-mahendra
  namespace: ns-mahendra
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: helloworld
